Feature_Card_Globale_Videos
WildCodeSchool/RMT-2203-TeamKarma-tigers pull request #34
Opened 2022-05-04 15:25 UTC by Robz53

2022-05-04 20:10 UTC, lchastanet requested changes

2022-05-04 20:10 UTC, lchastanet commented on frontend/package.json
> +    "nodemon": "^2.0.16",
This is useless here

2022-05-05 07:35 UTC, Robz53 commented on frontend/package.json
> +    "nodemon": "^2.0.16",
Fixed

2022-05-05 07:44 UTC, lchastanet approved these changes
Nickel 👌🏻

2022-05-05 07:44 UTC, merged